### ISSUE TITLE
Latest Chrome update 62.0.3202.94 causing freeze if <form> is present

### ISSUE THREAD

**Issue by MichalRemis** [AllenFang/react-bootstrap-table#1767] opened 2017-11-20 18:42 UTC
After latest Chrome update 62.0.3202.94 our clients (various platforms) reports that our app is unusable. I discovered really weird behaviour - **when `<form>` with inputs is present on web page with `<BootstrapTable>`, first time clicking (focusing) the (first) input causes browser to lag/freeze**. It depends on the count of rows/cells in bootstrap table. With complex table and slow computers the app is totally frozen.

I made JSFiddle to reproduce this - [https://jsfiddle.net/5asms7j7/116/ ]( https://jsfiddle.net/5asms7j7/116/ ). I tried to upgrade libs, but it seems that all react/react-bootstrap-table versions are affected. Only latest **Chrome v62** is affected. Firefox/Safari works fine.

I couldn't find what's causing this behaviour, but in our case I've found really ugly temporary workaround. Seems like only first `<input>` is affected so if I put another small - not meant to be used - input before inputs.. following inputs works ok.

**Comment by demenr** [comment] 2017-11-21 13:38
Oh I thought, I was the only one experiencing this problem. I have a table (with roughly 300 rows) and a modal windows which shows a form. Whenever I click on the first input available to type in, the page freeze. I will try your workaround, does it work if I put an hidden input?

**Comment by Fiorello** [comment] 2017-11-21 15:32
Same here.
Using the developer tools performance tab, I noticed that the mouse down event lasts over 10 seconds.

**Comment by demenr** [comment] 2017-11-22 16:10
@AllenFang do you have any clue why this is happening?

**Comment by mustafamamun** [comment] 2017-11-24 13:13
I tried to put a extra input in the beginning and then hide it using css. It works until I hide it.

**Comment by AllenFang** [comment] 2017-11-28 14:20
I'll spend some time to check, however, like I mentioned on README, `react-bootstrap-table` already stop development and start forward to [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop) and performance issue will be fixed on `react-bootstrap-table2` only.

**Comment by MichalRemis** [comment] 2017-11-28 15:49
Thank you for looking into it Allen. I think this isn't common performance issue, the lag is larger than just slow table rerendering and makes forms ununsable. Maybe you could have an idea if BootstrapTable is doing something with focus event handling of (unrelated) form inputs on page .

**Comment by mustafamamun** [comment] 2017-11-29 09:27
Could not find a npm package with the exact name react-bootstrap-table2. Only found [this](https://www.npmjs.com/package/react-bootstrap-table-2). Is this the right one?

**Comment by AllenFang** [comment] 2017-11-29 13:18
@MichalRemis ok, I'll look into on it
@mustafamamun `react-bootstrap-table2` not released yet, repo: https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop  it's still in progress.

**Comment by AllenFang** [comment] 2017-12-04 15:29
hi all,  please add `withoutTabIndex` prop on `BootstrapTable`. This prop default is `false` and it will add `tabIndex` on `td` element but I dont know the root cause, still investigating,  thanks

**Comment by AllenFang** [comment] 2017-12-04 15:32
not sure is about https://bugs.chromium.org/p/chromium/issues/detail?id=788933

**Comment by MichalRemis** [comment] 2017-12-05 15:09
thank you for solution @AllenFang , I confirm with `withoutTabIndex` freezing doesnt occur

**Comment by AllenFang** [comment] 2017-12-05 15:48
👍

**Comment by MichalRemis** [comment] 2017-12-19 10:55
With the latest Chrome update v63 this got fixed and it is not a problem anymore. @AllenFang I think this issue may be closed.

**Comment by AllenFang** [comment] 2017-12-21 13:51
thanks @MichalRemis, that's a good news, thanks your contribution :)

**Closed by AllenFang** 2017-12-21 13:51 UTC
Labels: in progress
