### ISSUE TITLE
Remote Paging page change issue

### ISSUE THREAD

**Issue by kaustav1992** [AllenFang/react-bootstrap-table#872] opened 2016-12-06 23:22 UTC
Hi,
 I'm able to fetch my data for different pages based on the page number and the code is reaching the onPageChange function and it modifies the page attribute in table options, but my value in the paginator is not changing although I change the page option in table options.

In the following screenshot, you can observe that I chose 3(page number), but 1 is still highlighted.
<img width="229" alt="screen shot 2016-12-06 at 3 17 42 pm" src="https://cloud.githubusercontent.com/assets/7247658/20948124/40eb5c20-bbc7-11e6-9421-c8ab8ea096fb.png">

**Comment by AllenFang** [comment] 2016-12-07 16:21
@kaustav1992, could you please show your code?  I guess you dont set ```page``` in ```options``` props?!

```js
render() {
    return (
      <BootstrapTable data={ this.props.data } remote={ true } pagination={ true }
                      fetchInfo={ { dataTotalSize: this.props.totalDataSize } }
                      options={ { sizePerPage: this.props.sizePerPage,
                                  onPageChange: this.props.onPageChange,
                                  page: this.props.currentPage,
                                  onSizePerPageList: this.props.onSizePerPageList } }>
        <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
        <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
        <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
```

**Comment by AllenFang** [comment] 2016-12-17 06:14
any updated?

**Comment by AllenFang** [comment] 2017-02-04 05:54
Close it due to no update

**Closed by AllenFang** 2017-02-04 05:54 UTC

**Comment by zhahaoyu** [comment] 2017-05-26 19:42
#1357

**Comment by p21asthana** [comment] 2017-06-09 12:25
I had the same issue. The problem is that if I am doing something like this options = { this.options } its not working, but when doing inline like options={ {
							clearSearch: true,
							paginationSize: 2,
							prePage: 'Prev',
							nextPage: 'Next',
							withFirstAndLast: false,
							sizePerPageList: [ 10, 25, 50 ],
							page: this.state.currentPage,
							onPageChange: this.onPageChange ,
							onSizePerPageList: this.onSizePerPageList
						} }
then its working. Any ideas?

**Comment by AllenFang** [comment] 2017-06-12 13:12
@p21asthana  be careful about using `this` in React component, for your case:  `this.options`. I dont think this is a bug

**Comment by shystruk** [comment] 2019-01-07 18:21
Hi guys,
I have the same issue. version 4.3.1. Pagination does not work in remote.
Any ideas, does anyone have a working version in remote?

I update page option on onPageChange callback.

```javascript
const options = {
    pageStartIndex: 1,
    paginationSize: 0,
    sizePerPage: 25,
    prePage: 'Previous',
    nextPage: 'Next',
    defaultSortOrder: '',
    defaultSortName: '',
    noDataText: 'No data',
    hidePageListOnlyOnePage: true,
    hideSizePerPage: true,
    ignoreSinglePage: true,
    page: 1
}

<BootstrapTable ref='table' remote={true} fetchInfo={{ dataTotalSize: 100 }} 
                             data={tableData} pagination={true} options={options}>
</BootstrapTable>
```
