### ISSUE TITLE
How to set width of Checkbox coloum 

### ISSUE THREAD

**Issue by Dhaval8087** [AllenFang/react-bootstrap-table#267] opened 2016-02-12 16:38 UTC
Hello,

I have implemented a checkbox column in table like 

selectRowProp = {
                    mode: this.props.recordSelectionType,
                    clickToSelect: true,
                    bgColor: "rgb(206, 239, 254)",
                    onSelect: onRowSelect,
                    onSelectAll: onSelectAll,
                    selected: selectedValues

                };
now in UI checkbox column it's taking so much width how I can set width of checkbox column ?

**Comment by staminaloops** [comment] 2016-02-13 00:38
Hello,
I cant reproduce it:
![image](https://cloud.githubusercontent.com/assets/11683210/13024237/eb46d97e-d1e9-11e5-9ebc-0ab1484be7c8.png)

Anyway, @AllenFang is on vacations (well deserved!), maybe he can help out when he comes back.
Meanwhile, can you give us a full example?

**Comment by AllenFang** [comment] 2016-02-15 13:10
@Dhaval8087, there's no way to set the width on selection column currently, but the problem of selection column it's taking so much width, I'll reduce its column size and make the checkbox align on center. But this improvement will be included in my new plan for fixing table column width problem so need some time:)

Thanks

**Comment by AllenFang** [comment] 2016-03-13 16:09
```v2.0.0``` has been released, you can check #331 for more detail explanation and I'll close this issues, if problem still remain, please tell me on #331 or open an issue.

**Closed by AllenFang** 2016-03-13 16:09 UTC
Labels: enhancement

**Comment by ronaiza-cardoso** [comment] 2019-01-29 16:51
hi, could you explain how I can do this?
