### ISSUE TITLE
React 16 gives unique key warning with autovalue={true}

### ISSUE THREAD

**Issue by FeNoMeNa** [AllenFang/react-bootstrap-table#1759] opened 2017-11-17 08:59 UTC
When we configure autovalue={true} for the key column of the table we are receiving the following warning. There is no problem If we present real id for the key column.

```
Warning: Each child in an array or iterator should have a unique "key" prop.
See https://fb.me/react-warning-keys for more information.
```

With React 15.* there is no problem. Please note that we are using the latest version of react-bootstrap-table.

**Comment by AllenFang** [comment] 2017-11-18 06:44
Hi @FeNoMeNa I can not reproduce this issue, any hint or example codes? thanks

**Comment by FeNoMeNa** [comment] 2017-11-19 12:26
Hi @AllenFang, thanks for your feedback. 

```js
  render () {
    const data = [
      {fname: 'Ivan', lname: 'Stefanov'},
      {fname: 'Jordan', lname: 'Stefanov'}
    ]

    return (
      <BootstrapTable data={data}>
        <TableHeaderColumn isKey hidden autovalue dataField='id' />
        <TableHeaderColumn dataField='fname'>First name</TableHeaderColumn>
        <TableHeaderColumn dataField='lname'>Last name</TableHeaderColumn>
      </BootstrapTable>
    )
}
```

Error:

```
warning.js:33 Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in tbody (created by TableBody)
    in table (created by TableBody)
    in div (created by TableBody)
    in TableBody (created by BootstrapTable)
    in div (created by BootstrapTable)
    in div (created by BootstrapTable)
```

- React 16
- Last version of react-bootstrap-table
- Linux / OSX
- Last versions of node and npm

**Comment by gravitycode** [comment] 2017-11-20 08:49
I have the same problem even generating the id manually and creating a hidden column as identifier

**Comment by AllenFang** [comment] 2017-11-21 13:11
@gravitycode performance issue will not fixed in `react-bootstrap-table`, we are forward to [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop).

**Comment by AllenFang** [comment] 2017-11-21 13:15
HI @FeNoMeNa I think there's some thing wrong in your code.

`autovalue` only useful when `insertRow`, because some people dont want the user keyin the rowkey, so we support a mechanism to generate rowkey auto.

However, your raw data doesn't have `id` field, in `react-bootstrap-table`, you are suppose to have a unique field, please find one our generate a sequential keys before render table.

Thanks

**Closed by AllenFang** 2017-11-21 13:15 UTC
