### ISSUE TITLE
No vertical scrollbars??

### ISSUE THREAD

**Issue by ddorsett** [AllenFang/react-bootstrap-table#1088] opened 2017-02-27 00:37 UTC
I have tried setting height and maxHeight properties on the table... but neither gives me a vertical scrollbar when there are clearly rows beyond the dimensions of the table.
Using 3.0.0. I moved up to this from 2.11. I don't recall seeing this with that version, but cant go back bc I need the customizable toolbar :(

**Comment by AllenFang** [comment] 2017-03-02 04:07
@ddorsett, sorry for  lately reply due to a long trip.

how many rows in a single page? have a screenshot for me to check ?  thanks

**Comment by ddorsett** [comment] 2017-03-06 23:23
I managed to get the vertical scrollbar to appear as I wanted by adding a specific adjustment: subtracting 70px from the height of the div that the table is rendered into and setting the height property to that,
I have a custom toolbar and btnGroup, dont know if that would make a difference

**Comment by AllenFang** [comment] 2017-03-08 14:34
I may to see what's your are doing will probably know what's going on. and I think this is not a bug for `react-bootstrap-table` so that I'll close this issue, but let me know you you have any question, thanks

**Closed by AllenFang** 2017-03-08 14:34 UTC
