### ISSUE TITLE
Modal will close automatically by clicking field on react-bootstrap@0.29.x

### ISSUE THREAD

**Issue by StefanoGitHub** [AllenFang/react-bootstrap-table#412] opened 2016-04-20 08:22 UTC
Hi @AllenFang,
I am creating tables within `react-bootstrap Tabs`.
In the table's modal that appears for adding a new row, when I click on any field to insert data the modal just disappears, the table also disappears and the app freezes showing the grey layer.
At the click on the field in the modal, the Tab's `handleSelect()` is called (probably the `select` event on the modal's input field bubbles up to the Tab?) as it logs what I believe it is the event object itself.

This is my code:
```
var ReactBsTable = React.createClass({
    render: function () {
        return (
            <BootstrapTable id="table" ref="table"
                            data={products}
                            insertRow={true}
                            striped={true}
                            hover={true}
                            deleteRow={true}
                            selectRow={selectRowProp}
                            exportCSV={true}
                            csvFileName={'table.csv'}
                            options={optionsObj}
                            >
                <TableHeaderColumn 
                           dataField="id" 
                           isKey={true} 
                           autoValue={true}>Product ID</TableHeaderColumn>
                <TableHeaderColumn dataField="name">Product Name</TableHeaderColumn>
                <TableHeaderColumn dataField="price">Product Price</TableHeaderColumn>
            </BootstrapTable>
        );
    }
});

...

var Menu = React.createClass({
    getInitialState: function () {
        return {key: 2};
    },
    
    handleSelect: function (key) {
        console.dir(key);
        this.setState({key});
    },
    
    render: function () {
        return (
            <Tabs activeKey={this.state.key} 
                       onSelect={this.handleSelect} 
                       animation={false} >
                <Tab eventKey={1} title="Tab 1" id="tab1">Tab 1 content</Tab>
                <Tab eventKey={2} title="Tab 2" id="tab2">
                    <ReactBsTable />                
                </Tab>
                <Tab eventKey={3} title="Tab 3" id="tab3">Tab 3 content</Tab>
            </Tabs>
        );
    }
});
```

Do you have any suggestion?
I am completely new to react so I apologize if it is just some trivial mistake.
Thanks!

**Comment by AllenFang** [comment] 2016-04-20 11:35
don't mind, @StefanoGitHub, what's the version for bootstrap?

**Comment by StefanoGitHub** [comment] 2016-04-20 14:37
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js
https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js
https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap/0.29.0/react-bootstrap.min.js

**Comment by AllenFang** [comment] 2016-04-20 15:19
@StefanoGitHub, what's that https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js?   I thinks you can remove it first and test again.  :)

**Comment by AllenFang** [comment] 2016-04-20 16:43
ok, I'll check this out, maybe it's a bug only happen on table in the tabs.

**Comment by AllenFang** [comment] 2016-04-21 12:54
@StefanoGitHub, could you please show you whole examples, because I follow your snippet but can't reproduce it. Thanks

**Comment by StefanoGitHub** [comment] 2016-04-22 00:16
@AllenFang I have just sent you an email with my code, please confirm you received it.

**Comment by AllenFang** [comment] 2016-04-22 01:55
@StefanoGitHub, I see it. Thanks :)

**Comment by AllenFang** [comment] 2016-04-23 06:04
@StefanoGitHub, This problem is using ```react-bootstrap``` at ```v0.29.0```. You can downgrade to ```v0.28.x``` will fix this issue. BTW,  ```v0.28.x``` depend on ```react@0.14.x```, so you need also downgrade the react version. Anyway, I'll keep to figure out why ```react-bootstrap@0.29``` will cause this issue.

**Comment by trishfromtisch** [comment] 2016-06-01 15:51
Hi there,

Thanks for this amazing library, Allen!  I was wondering if you have a fix for this issue; I'm still having problems with the modal closing, even without clicking anywhere.  I installed react-boostrap@0.28.5 with npm, but am still having this problem. 

Thanks,
Trish

**Comment by StefanoGitHub** [comment] 2016-06-01 16:32
I've recently switched to `npm` and I'm using
`"react": "^15.0.2", "react-bootstrap": "^0.29.4", "react-bootstrap-table": "^2.3.1",`
everything work just fine! :)

**Comment by StefanoGitHub** [comment] 2016-06-01 17:30
Actually, just noticed that if I do not import the `bootstrap` library at the top of my page (`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
        crossorigin="anonymous"></script>`) the modal for inserting a new value doesn't popup at all.

I tried also installing `bootstrap` with `npm` in my project (`"bootstrap": "^3.3.6"`), even if I believe it should be included already in the `react-bootstrap` library, but it doesn't help...
@AllenFang am I missing something? Should I import `bootstrap` in my components file maybe?

**Comment by trishfromtisch** [comment] 2016-06-01 17:38
Thanks for getting back to me so quickly, Allen; you're a rockstar!

`<div class="modal fade bs-table-modal-sm**2635**" tabindex="-1" role="dialog" style="display: none;">` 

If I inspect the DOM with Chrome dev tools, it shows the class name bs-table-modal-sm[n] incrementing by 1 every second -- maybe it's reinstantiating the modal in an infinite loop somewhere?  Sorry if that doesn't help.

**Comment by AllenFang** [comment] 2016-06-02 12:25
@StefanoGitHub, you should always import or bundle```bootstrap.js```. BTW, I've used ```bootstrap``` installed from ```npm``` and integrated with ```bootstrap-loader```, it work fine with ```react-bootstrap-table```(I've two project used it). And I'm surprised you can work on ```react-bootstrap@0.29.x```

@trishfromtisch, did you add ```bootstrap.js``` in html or bundle it to dist? that's said, if you click button for adding row, I'll give a unique class name ```bs-table-modal-sm[n]``` for modal, ```n``` is a sequence number handled in component. So there must have a problem cause the render method sill be called.
I've no idea about that, could you please show your example code and the version(react, bootstrap,..etc) you used

**Comment by trishfromtisch** [comment] 2016-06-02 14:09
Hi @AllenFang --thanks for this truly awesome library, and for getting back to me!  I've figured out that setState was being called in an infinite loop in my parent component, which was causing the table to reload, and the modal to disappear.

**Comment by AllenFang** [comment] 2016-06-02 14:47
@trishfromtisch, I'm glad that you found the root cause and just enjoy this component :)
Feel free to ask me anything, Thanks

**Closed by AllenFang** 2016-06-02 14:47 UTC

**Comment by StefanoGitHub** [comment] 2016-06-02 16:16
@AllenFang just out of curiosity, why do I need to import `bootstrap.js` if I'm already using `react-bootstrap` for other components, and your library is based on that too, right?
Isn't (shouldn't be) the 'bootstrap' library already included in your code/library?

Also, reading from `react-bootstrap` [docs](https://react-bootstrap.github.io/getting-started.html#commonjs):
> React-Bootstrap is a complete re-implementation of the Bootstrap components using React. It has no dependency on either bootstrap.js or jQuery. If you have React setup and React-Bootstrap installed you have everything you need.

Anyway, you might want to specify that in your doc, it would make it more clear.
Thanks again!

**Comment by AllenFang** [comment] 2016-06-04 05:52
@StefanoGitHub, sorry for lately reply. I'm not sure that ```react-bootstrap``` does bundle ```bootstrap.js```(It seems not),  I'll test it in near future. :)
Thanks 👍
