### ISSUE TITLE
Getting row index onRowClick

### ISSUE THREAD

**Issue by amx93** [AllenFang/react-bootstrap-table#1296] opened 2017-05-08 14:45 UTC
onRowClick: this.modalClick()
modalClick(row, index){...

index value undefined

**Comment by AllenFang** [comment] 2017-05-09 15:47
Too few information for me to reproduce, please shoe me your case due to [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/row-click-table.js) still work well.

close it because lack of information.

**Comment by prajapati-parth** [comment] 2017-07-11 09:58
Hi @AllenFang, I just came across this issue. I think what @amx93 need was the rendered row index. 
Eg. If there are total 15 rows with 5 rows on each page, clicking on the 5th row of each index should get a number 4. 
Specifically the number that you use [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/TableBody.js#L160)

This would be irrespective of the sort or pagination. Every time a visually displayed 3rd row is clicked, it's index 2 should be received even if it is sorted.

**Comment by prajapati-parth** [comment] 2017-07-11 10:06
This can be solved by replacing [this line](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/BootstrapTable.js#L665) with
```
options.onRowClick(row, columnIndex, rowIndex);
```
Thanks.

**Comment by AllenFang** [comment] 2017-07-13 13:05
@prajapati-parth thanks your 👍   I'll add `rowIndex` as third parameter for `options.onRowClick`.

**Closed** 2017-07-13 15:24 UTC
Labels: help wanted, in progress

**Comment by AllenFang** [comment] 2017-07-13 15:26
@prajapati-parth it was fixed on `v3.4.5`, thanks

**Comment by 9005** [comment] 2018-01-10 06:24
For the below code I get undefined for columnIndex and rowIndex.
 onRowClick:function(row,columnIndex,rowIndex,e){
          console.log(`${columnIndex}`);
        }

need help!!

**Comment by PriyankaMGK** [comment] 2018-01-31 06:16
How can i set the serial number starts from 1 dynamically in react bootstrap table.
my json would be getdata={  
   "data":{  
      "List":[  
         {  
            "name":"React"
         },
         {  
            "name":"Javascript"
         }
      ]
   }
};
<BootstrapTable data={ getdata } striped hover pagination={ true }  options={ options }  search={ true }>
<TableHeaderColumn true dataField='what' isKey={true} dataAlign="center">S.No</TableHeaderColumn>
 <TableHeaderColumn dataField='name' dataAlign="center" dataSort={ true }> Name</TableHeaderColumn>
</BootstrapTable>

**Comment by PriyankaMGK** [comment] 2018-01-31 06:16
<TableHeaderColumn true dataField='what' isKey={true} dataAlign="center">S.No</TableHeaderColumn>
