### ISSUE TITLE
New props doesn't trigger a full re-render

### ISSUE THREAD

**Issue by cruz02148** [AllenFang/react-bootstrap-table#881] opened 2016-12-09 22:41 UTC
Hello,

I have a simple two column table with the first column being radio buttons and the second being the name/label for these buttons. I looked through the examples to find a way to make a custom header so that when I enable the `selectRow` prop so I can have the header of the radio buttons say "Select One" because by default it is just an empty box. 

So now my problem is that I want to be able to set the `checked` attribute of the radio buttons. The reason for this is that I;m using Redux to keep track of what the user selected once they hit a "Save and Continue" button on the page. So if they were to navigate back to this component with the Table, I want whatever radio button they had selected to be `checked` for them.

Below if the code I have in my `customComponent` function which I took from here: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/custom-multi-select-table.js

```
customMultiSelect(props) {
    const { type, onChange, rowIndex } = props;
    if (rowIndex === 'Header') {
      console.log('Header: ', this.props.savedTemplate)
      return (
        <div>Select One</div>
      );
    } else {
      console.log('else: ', this.props.savedTemplate);
      const templates = this.props.templates.map(template => template.name);
      const uniqueID = templates[this.index].replace(' ', '-').toLowerCase();
      const templatesToRender = (
        <div>
          <input
            id={`${uniqueID}-sms-template`}
            type={ type }
            name="template"
            onChange={ e=> onChange(e, rowIndex) }
          />
        </div>
      );
      this.index++;
      return templatesToRender;
    }
  }
```

I'm also running `componentWillReceiveProps` to check for the new props. I would then mostly likely call `setState` here to update the state and use this value to set the checked value. However, the bug problem is that when the component re-renders after `componentWillReceiveProps` is executed, the entire component doesn't re-render as it appears that only the 'Header` index is re-rendered. You can see up in my code snippet on the fourth and ninth lines I have two `console.log` statements to help me debug. At first, both statement execute like normal, however, once I select a radio button, hit "Save and Continue" to go to a new component and then I navigate back to this table component, only the `console.log('Header', ....)` statement runs and I'm not sure why. See below for a timeline of the console.log statements in the browser:

```
render
SMSTemplates.js:53 SMSTemplate componentWillReceiveProps:  
SMSTemplates.js:142 render
SMSTemplates.js:64 Header:  
3SMSTemplates.js:77 else:  
THIS IS THE FIRST RENDER!
SMSTemplates.js:64 Header:  
SMSTemplates.js:77 else:  

AFTER THIS LINE IS WHAT HAPPENS WHEN I NAVIGATE BACK TO THE TABLE COMPONENT.....
VM285406:1 Uncaught SyntaxError: Unexpected identifier
SMSTemplates.js:142 render
SMSTemplates.js:64 Header:  
3SMSTemplates.js:77 else:  
SMSTemplates.js:53 SMSTemplate componentWillReceiveProps:  Some Text
SMSTemplates.js:142 render
SMSTemplates.js:64 Header:  Some text
```

Any help would be appreciated as I've been stuck on this all day

**Comment by AllenFang** [comment] 2016-12-12 13:55
hi @cruz02148, sorry for lately reply, I'll check this out.  Your explanation is very well. 👍

**Comment by AllenFang** [comment] 2016-12-12 14:08
I would like to know how you configure the ```selectRow``` on```BootstrapTable```, thanks :)

> So now my problem is that I want to be able to set the checked attribute of the radio buttons

You mean you want to check the radio on header that you custom or in the columns in body?

**Comment by AllenFang** [comment] 2016-12-12 14:20
BTW, you said you use redux, and how did you tell the ```react-bootstrap-table``` which row is selected?

**Comment by cruz02148** [comment] 2016-12-14 17:46
hi @AllenFang, thanks for responding! I actually ended up writing my own custom component table to serve my specific need, but I'll reply here to help out any way I can.

This was my `selectRow` props options object:
```
const selectRowProp = {
     mode: 'radio',
     customComponent: this.customMultiSelect,
     onSelect: this.onRowSelect
   };
```
And to clarify your question "You mean you want to check the radio on header that you custom or in the columns in body?" -- Each row of the table will have a radio button in column1 and the name of the of radio button in column2. So what I wanted was to have the particular **row** be selected based on what the user had previously saved, which I then sent to the Redux store.

In the BootstrapTable I had the following option `data={this.props.templtes}` so the table knew what data to render. `this.props.templates` came from the Redux store. So my goal was to set the checked` value of the input equal to whether or not the value of the input was equal to the current template value stored in Redux. However, I could not get to this step as whenever I navigated away from this component and then came back, the table would not render past the `Header` row. You can see my `console.log` statements to see what I mean. I was going  to do some logic in `componentWillReceiveProps` and you can see how the `console.log('else'`)` statements executes 3 times the first time the component renders, but fails to do so if I navigate away from it and try to come back.  Below is the code snippet from above for conveniece and clarity: 

```
render
SMSTemplates.js:53 SMSTemplate componentWillReceiveProps:  
SMSTemplates.js:142 render
SMSTemplates.js:64 Header:  
**_3_SMSTemplates.js:77 else:**  
THIS IS THE FIRST RENDER!
SMSTemplates.js:64 Header:  
SMSTemplates.js:77 else:  

AFTER THIS LINE IS WHAT HAPPENS WHEN I NAVIGATE BACK TO THE TABLE COMPONENT.....
VM285406:1 Uncaught SyntaxError: Unexpected identifier
SMSTemplates.js:142 render
SMSTemplates.js:64 Header:  
**_3_SMSTemplates.js:77 else:**  
SMSTemplates.js:53 SMSTemplate componentWillReceiveProps:  Some Text
SMSTemplates.js:142 render
SMSTemplates.js:64 Header:  Some text
```

**Comment by AllenFang** [comment] 2016-12-16 00:48
@cruz02148, really thank your description, that's enough to me and I'll figure out what's going on.

**Comment by AllenFang** [comment] 2016-12-17 07:41
@cruz02148, I have another question at below:


> So what I wanted was to have the particular row be selected based on what the user had previously saved, which I then sent to the Redux store

As I guess, you save the row that user saved in the redux store, and populate these saved row into component and make these row as selected on table, right? 

so my question is , how you make these row as selected on table? you should use ```selected``` in ```selectRow``` props, but I don't saw it.

Anyway, because I've no idea about this issue, so could you please show me a minimal and simple code to me to reproduce? I think I can be reproduced without redux.

Thank a lots

**Comment by cruz02148** [comment] 2016-12-17 21:52
@AllenFang I'm working on trying to reproduce the error, but in doing so I think that there is a solution for my problem already. You led me back to trying the `selected` attribute in `selectRow` so I'm trying to use that. However, I can't get the `selected` value to work. 

I have a table 3 rows. and 2 columns. The first column is a radio input and the second column is the name of the radio button (i.e. Program 1). So in my 'selectRow' prop I am trying the following:
```
const selectRowProp = {
      mode: 'radio',
      customComponent: this.customMultiSelect,
      onSelect: this.onRowSelect,
      selected: ['Program 1']
    };
```
Just to test out that I can get something selected, I have just assigned the selected value to 'Program 1' which is equal to the name of the cell. However, when the table renders, there is no selected value that is set when using this setup.

Below is my Table component:

```
<BootstrapTable data={this.props.templates} selectRow={ selectRowProp }>
            <TableHeaderColumn
              width="100"
              isKey={true}
              dataField='name'
              dataFormat={this.formatTemplateItem}
            >Product Name
            </TableHeaderColumn>
          </BootstrapTable>
```
You can see the `dateField='name'` i have assigned. I would think this is they `key` that `selected` expects. Since I can't get it to work, I suspect that there is a problem with using `selected` with radio buttons rather than the checkboxes in the examples? 

If I'm able to use `selected` with radio buttons then I think I will be able to solve my original problem of having a "checked"/"selected" value in the table that is populated from Redux.

Thanks!

**Comment by AllenFang** [comment] 2016-12-18 05:54
ok, I think I can close this issue, but if you still have any problem, please let me know :)

BTW, the ```selected``` accept a array which should contain the rowKey, so if you have time, you can give a try!

**Closed by AllenFang** 2016-12-18 05:54 UTC
Labels: inprocess

**Comment by cruz02148** [comment] 2016-12-18 19:50
@AllenFang so I tried using `selected`, but it doesn't seem to work when also using the `customComponent` attribute in `selectProp`. I tested this out with my own code and confirmed this. Is there another way to use `selected` when combined with `customComponent`?

So I tried accomplishing my goal a different way... by setting the `checked` value of the input inside my `customComponent` function although it is not fully working.

Below is my entire component: 
```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import * as actions from './actions';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

class SMSTemplate extends Component {
  constructor(props) {
    super(props);
    this.state = { tempVal: '' };
    this.customMultiSelect = this.customMultiSelect.bind(this);
    this.formatTemplateItem = this.formatTemplateItem.bind(this);
    this.onRowSelect = this.onRowSelect.bind(this);
    this.showPreview = this.showPreview.bind(this);
  }

  customMultiSelect(props) {
    const { type, onChange, rowIndex } = props;
    if (rowIndex === 'Header') {
      return (
        <div>Select One</div>
      );
    } else {
      console.log('else statement!')
      const uniq = this.props.templates[rowIndex].name;
      const { tempVal } = this.state;
      const { savedTemplate } = this.props;
      console.log('demo: ', tempVal === uniq || (uniq === savedTemplate && !tempVal));

      const templatesToRender = (
        <div>
          <input
            type={type}
            value={uniq}
            checked={tempVal === uniq || (uniq === savedTemplate && !tempVal)}
            name="template"
            onChange={ e=> onChange(e, rowIndex) }
          />
        </div>
      );
      return templatesToRender;
    }
  }

  formatTemplateItem(cell, row) {
    return <a id="format-template-item-sms" onClick={() => this.showPreview(row)}>{cell}</a>
  }

  onRowSelect(row, isSelected, e) {
    this.setState({ tempVal: row.name });
    this.props.changeSMSRadio();
    this.props.updateContentPreview(row);
  }

  showPreview(row) {
    this.props.renderPreview();
    this.props.updateSMSPreview(row);
  }

  render() {
    const selectRowProp = {
      mode: 'radio',
      customComponent: this.customMultiSelect,
      onSelect: this.onRowSelect,
    };
    if (!this.props.templates) {
      return <div>Loading...</div>
    } else {
      return (
        <div>
          <label>Select a template for the SMS message:</label>
          <BootstrapTable data={this.props.templates} selectRow={ selectRowProp }>
            <TableHeaderColumn
              width="100"
              isKey={true}
              dataField='name'
              dataFormat={this.formatTemplateItem}
            >Product Name
            </TableHeaderColumn>
          </BootstrapTable>
        </div>
      );
    }
  }
}

export default connect(null, actions)(SMSTemplate);
```

If you look at the `else` block inside the `customMultiSelect` function you can see how I am trying to set the checked value. Basically, it should either be equal to the current state, which should be getting set after the user clicks on a row OR if the user has saved a selection, navigates to another page, then comes back, it should then be equal to the saved value inside the Redux store (`this.props.savedTemplate`).  The exact issue I'm facing is that when the users then tries to select a new value (after having saved one in Redux), the item that was previously "saved" is always the one checked, even though the `state` has been updated to equal the new selection and I believe should then trigger the expression `tempVal === uniq` instead of `uniq === savedTemplated && !tempVal`

**Comment by AllenFang** [comment] 2016-12-19 12:02
I'll run your code in my local and try to figure out what's happening, thanks your effort!

**Comment by AllenFang** [comment] 2016-12-19 14:57
BTW, following are a little example for ```selected```
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/default-select-table.js
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/externally-managed-selection.js

**Comment by AllenFang** [comment] 2016-12-19 15:08
ok, I understand what's the problem you encounter, I think I need to setup an environment to reproduce this issue, so this will take some time
