### ISSUE TITLE
PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by shadow-identity** [AllenFang/react-bootstrap-table#1278] opened 2017-05-03 11:30 UTC
Hello,
In 3.3.0, in SelectRowHeaderColumn proptypes defined as 
```
SelectRowHeaderColumn.propTypes = {
  children: _react.PropTypes.node,
  rowCount: _react.PropTypes.number
};
```
It causes Deprecation warning on React:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

React recommends to use prop-types npm package: https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by AllenFang** [comment] 2017-05-03 13:52
There's a PR https://github.com/AllenFang/react-bootstrap-table/pull/1253 for fixing it, please wait, thanks

**Comment by aliceathens** [comment] 2017-05-25 05:53
Do you have an ETA on this? Unit tests are failing because of this error. Thanks!

**Comment by AllenFang** [comment] 2017-05-29 14:46
It was fixed on `v4.0.0-beta.5` and ETA may in the second or third week on June

**Comment by ofirgeller** [comment] 2017-06-25 12:23
@AllenFang I think the dist files were not updated when v4.0.0-beta-6 (and 5) were commited. I checked and they still have ` React.PropTypes ` in them, you might not be seeing the warnings because you are running via a build system, but when I try depending on this commit I do get the warning.

**Comment by DavidDiscua** [comment] 2017-07-04 05:20
@ofirgeller  Same issue for me.

**Comment by AllenFang** [comment] 2017-07-08 06:43
I'll check, thanks 👍

**Comment by DavidDiscua** [comment] 2017-07-08 06:45
I fix it using beta 6... 🤔.

**Comment by AllenFang** [comment] 2017-07-08 09:28
@DavidDiscua, oh really, I doesn't check yet but it might be not a bug, @ofirgeller, could you please confirm this issue again, thanks

**Comment by ofirgeller** [comment] 2017-07-08 12:23
@AllenFang  Fixed for me in 4.0.0-beta-6

**Comment by AllenFang** [comment] 2017-07-09 06:13
@ofirgeller, nice 👍 thanks your response 👍

**Comment by pyronicide** [comment] 2017-07-13 14:48
Looks broken again in 4.0.0-beta-7 again.

**Comment by jtheberge** [comment] 2017-07-15 02:28
Also broken in beta-7 for me

**Comment by AllenFang** [comment] 2017-07-16 05:42
hey folks, I'll fix it in next beta version, sorry

**Comment by AllenFang** [comment] 2017-07-16 09:38
upgrade to `v4.0.0-beta.8`, let me know if the problems still remains, thanks

**Closed** 2017-07-16 09:38 UTC
Labels: 4.0.0, in progress

**Comment by jtheberge** [comment] 2017-07-17 21:30
Hey @AllenFang! Unfortunately, the issue still exists for me in beta.8. Thanks for your work so far!

**Comment by AllenFang** [comment] 2017-07-18 08:30
@jtheberge, thanks, Seems like i forgot change [this](https://github.com/AllenFang/react-bootstrap-table/blob/v4.0.0-dev/src/ExpandRowHeaderColumn.js#L1)   lol
