### ISSUE TITLE
Uncaught TypeError: Cannot read property 'refs' of undefined on selecting tab

### ISSUE THREAD

**Issue by davecarlson** [AllenFang/react-bootstrap-table#156] opened 2015-11-27 14:19 UTC
In Google Chrome (mac), when I select a tab of another page , then go back to the tab with the table on, i get multiple instances of this.

Uncaught TypeError: Cannot read property 'refs' of undefined_adjustHeaderWidth @ BootstrapTable.js:609

**Comment by AllenFang** [comment] 2015-11-27 14:35
@davecarlson , I cant reproduce this problem but did you got another problem or bugs when this error printed?

**Comment by staminaloops** [comment] 2015-11-27 14:37
I'm having this error too. Try to resize the window and see if you can reproduce it too.

**Comment by davecarlson** [comment] 2015-11-27 14:41
@staminaloops  - yes, resizing the window gets the same error.

**Comment by AllenFang** [comment] 2015-11-27 14:45
wow, that‘s strange, I cant reproduce again ;(  Anyway, there's any header unalign problem after window resizing?

**Comment by staminaloops** [comment] 2015-11-27 14:47
no everything works, just Uncaught TypeError: Cannot read property 'refs' of undefined

**Comment by AllenFang** [comment] 2015-11-27 14:48
@staminaloops, thanks, I'll keep an eye on this problem and try to reproduce it !

**Comment by staminaloops** [comment] 2015-11-27 14:51
![error-table](https://cloud.githubusercontent.com/assets/11683210/11443585/2c148020-9516-11e5-9539-947c299fec37.png)

Everytime we resize the window, it add +1 error :) Thank you @AllenFang

**Comment by AllenFang** [comment] 2015-11-27 14:52
:+1:

**Comment by AllenFang** [comment] 2015-11-27 15:04
I find this problem, I should no bind <code>this</code> with <code>_adjustHeaderWidth</code> when remove window resizing event @BootstrapTable.js:122. Thanks for this bug report, I'll fix it on next version :)

**Comment by davecarlson** [comment] 2015-11-30 14:55
Is this in v1.2.14 ?

**Comment by AllenFang** [comment] 2015-11-30 15:54
@davecarlson, sorry for my promise. It's not fixed in v1.2.14, however, I'll fix it in these day :)

**Comment by AllenFang** [comment] 2015-12-01 12:46
Fix it in v1.2.15

**Closed** 2015-12-01 12:45 UTC

**Comment by davecarlson** [comment] 2015-12-03 14:02
Confirmed. Thanks !

**Comment by kadariyp** [comment] 2017-05-16 19:55
I am using ^4.0.0-beta.1 right now and i face the same issue. It fails on componentWillUnmount function, inside BootstrapTable.js.

**Comment by kadariyp** [comment] 2017-05-16 19:55
this.refs.body.refs.container.removeEventListener('scroll', this._scrollHeader);

**Comment by AllenFang** [comment] 2017-05-17 12:32
@kadariyp, only happen on `v4.0.0`?

**Comment by kadariyp** [comment] 2017-05-17 13:48
@AllenFang I tried it with the latest non beta version and i still get the error. It happens on selecting the tab that mounts and unmounts the table. So I think the bug is similar to the one mentioned here.

**Comment by EmilAgren** [comment] 2017-05-18 21:02
I'm also getting exactly the same error as @kadariyp is talking about (using react-bootstrap-table 3.3.5).

**Comment by AllenFang** [comment] 2017-05-19 16:31
try to upgrade `v3.3.6`~

**Comment by EmilAgren** [comment] 2017-05-19 21:12
Unfortunately still the same problem after upgrade to 3.3.6.
The problem started when I started using webpack. When using react-bootstrap-table just by importing the necessary script in index.html it works perfectly.

**Comment by AllenFang** [comment] 2017-05-20 08:52
it's wired, could you post your error message?

**Comment by EmilAgren** [comment] 2017-05-20 09:19
This is what I'm getting: 

![err2](https://cloud.githubusercontent.com/assets/4100810/26274614/dfe9b882-3d4d-11e7-85f0-0dc5b1f0ca70.PNG)

**Comment by AllenFang** [comment] 2017-05-22 15:09
ok, I'll check this out, but not sure if I can fix it

**Comment by EmilAgren** [comment] 2017-05-25 08:22
Solved it, and It was my mistake. I tried to reinstall all of my node modules which solved the problem.
My guess is that I must have had multiple copies of React loaded somehow.
Anyway, thanks for your time and a great component :)
