### ISSUE TITLE
table missing style, css

### ISSUE THREAD

**Issue by fachhoch** [AllenFang/react-bootstrap-table#855] opened 2016-11-23 04:28 UTC
I am learning react, new bee ,  trying bootstrap table, table  renders, but without any style  , I am missing something, my table class src below , I  included css using   [`import 'react-bootstrap-table/dist/react-bootstrap-table-all.min.css'`]   not sure if this is write?,   this project is in  github,  [project link](https://github.com/fachhoch/react-gs.git)

 ```
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';
import 'react-bootstrap-table/dist/react-bootstrap-table-all.min.css';

const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(70);

export default class DefaultPaginationTable extends React.Component {
  constructor(props) {
    super(props);
  }
  renderShowsTotal(start, to, total) {
    return (
      <p style={ { color: 'blue' } }>
        From { start } to { to }, totals is { total }&nbsp;&nbsp;(its a customize text)
      </p>
    );
 }
  render() {

		const options = {
			 page: 1,
			 sizePerPageList: [ {
		        text: '5', value: 5
		      }, {
		        text: '10', value: 10
		      }, {
		        text: '20', value: 20
		      } ]
		      ,sizePerPage: 5,  // which size per page you want to locate as default
		      pageStartIndex: 0, // where to start counting the pages
		      paginationSize: 10,  // the pagination bar size.
		      prePage: 'Prev', // Previous page button text
		      nextPage: 'Next', // Next page button text
		      firstPage: 'First', // First page button text
		      lastPage: 'Last', // Last page button text
		      paginationShowsTotal: this.renderShowsTotal

		};
    return (
      <div>
        <BootstrapTable data={ products } pagination={ true } options={options} >
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
      </div>
    );
  }
}`
```

image of rendered table
![rbdt](https://cloud.githubusercontent.com/assets/450078/20551091/5a7fd994-b10a-11e6-99f7-8b60946230f5.PNG)

**Comment by fachhoch** [comment] 2016-11-23 13:42
applying jquery and bootstrap  script and link tag resolved the issue.

```
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
```

**Comment by email2vimalraj** [comment] 2016-11-25 06:02
@fachhoch : If the issue is resolved, feel free to close it by yourself please.

**Closed** 2016-11-25 16:11 UTC

**Comment by AllenFang** [comment] 2016-11-27 06:27
@fachhoch, In near future, ```bootstrap.min.js``` and ```jQuery``` this both dependency will be removed on ```v3.0.0```. Anyway, you can check ```v3.0.0-beta.2```.

**Comment by maulikdesai21** [comment] 2017-08-03 15:18
@AllenFang : I am using v3.5.1  are the dependencies removed? I was unable to make it work without the dependencies

**Comment by AllenFang** [comment] 2017-08-03 15:20
1. Remember to import the css of `react-bootstrap-table`
2. No need `bootstrap.js` anymore.

**Comment by maulikdesai21** [comment] 2017-08-03 15:49
This is the react component that I am trying to use react-bootstrap-table

`import React from 'react';

import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';
var products = [{
  id: 1,
  name: "Product1",
  price: 120
}, {
  id: 2,
  name: "Product2",
  price: 80
},{
  id: 1,
  name: "Product1",
  price: 120
}, {
  id: 2,
  name: "Product2",
  price: 80
}];
class AccessList extends React.Component{
  constructor(props) {
    super(props);

  }
  render() {
    return (
      <div>
        <BootstrapTable data={ products } striped hover condensed>
          <TableHeaderColumn dataField='id' isKey>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
        </BootstrapTable>
      </div>
    );
  }

}
module.exports = AccessList;`

This is the main component that serves as a container for all my components, where I imported the CSS 
`import React from 'react';
import ReactDOM from 'react-dom';
import './css/style.css';
import './css/style.css';
import '../node_modules/react-bootstrap-table/dist/react-bootstrap-table.min.css';
import App from './components/App'

import  'adp-css-framework';

ReactDOM.render(<App />,document.getElementById('root'));`

This does not work. I work only if I add **bootstrap.min.css** & **jquery** in my HTML as shown below  
`<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>

</head>
<body>
<div id='root'></div>
</body>
</html>`

Not sure if I am doing something wrong as I am still quite a rookie at REACT

**Comment by AllenFang** [comment] 2017-08-05 08:51
I'm not sure what's going on in your repo, could I have a demo repo to reproduce this one? Please give me a repo for me, I will help you to check, thanks

**Comment by sharyleo** [comment] 2017-11-01 08:47
Hi, 
I also face same problem like @maulikdesai21 

I do import as below:

import React from 'react';
import 'react-bootstrap-table/dist/react-bootstrap-table-all.min.css'
import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table'

and the result is without css,
Please assist, thanks!

**Comment by norbusan** [comment] 2017-11-07 04:19
I am doing something very similar with electron+react, and there not even the import statement works out.

**Comment by Vequan23** [comment] 2017-11-16 17:23
Is there a fix for this yet? My import statement is not working either.

**Comment by AllenFang** [comment] 2017-11-18 06:31
hey guys, I dont think there's any issue there, please give me a repo and to show me the problem. and please write a good readme for me to setup your code

**Comment by shal-xu** [comment] 2017-11-22 19:58
@AllenFang I think below is an easy illustration of the problem that I and some other people faced.

I found these two jsFiddles of react-bootstrap-table on Google for reference. None of their stylings work.
https://jsfiddle.net/omerts/5asms7j7/
https://jsfiddle.net/03h4dvav/

However, if you add `https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css` to the `External Resources` tab on the left, both of the examples now work.

These two examples seem to indicate that, people are not aware they need to import the bootstrap css file.

**Comment by AllenFang** [comment] 2017-11-26 13:42
I see, I'll write some indication to mention this.. @shal-xu thank you

**Comment by ghostrider1255** [comment] 2019-10-16 13:39
@AllenFang : I am facing the same issue. I have imported the table css. as below but the styling is not working for my pagination table.
import 'react-bootstrap-table/dist/react-bootstrap-table-all.min.css'
import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table'

however Adding the CDN (as show below) to my index.html makes the styling applied to the table but screwing up my all other stylings. Is there a fix so that i don't have to add this bootstrap link and still it works with just above two imports . Please help me in this regard. 
 
"<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"  >"

Below are my dependencies
"react-bootstrap": "^1.0.0-beta.14",
 "react-bootstrap-table": "^4.3.1",
"bootstrap": "^4.3.1",

**Comment by athina635** [comment] 2020-06-02 13:14
@AllenFang 
 

> however Adding the CDN (as show below) to my index.html makes the styling applied to the table but screwing up my all other stylings. Is there a fix so that i don't have to add this bootstrap link and still it works with just above two imports . Please help me in this regard.


Any solution for this ? 
the bootstrap.min.css destroy the old page design when import it into he index.html
