### ISSUE TITLE
Pagination drop down requires double click

### ISSUE THREAD

**Issue by Kawirider636** [AllenFang/react-bootstrap-table#1570] opened 2017-08-23 16:05 UTC
I'm having an issue where you have to click the pagination drop down button twice before the list of number per page drop down shows. I've noticed on the examples page[http://allenfang.github.io/react-bootstrap-table/example.html] there is a similar experience. You can click it the first time it will show, if you don't change it and click off, and then click the button again nothing happens, a second click is required to show the drop down. 

`render() {
		const options = {
			expandRowBgColor: 'rgb(242, 255, 163)',
			
		};
		const statuses = {
			0: 'Pending',
			1: 'Approved',
			2: 'Rejected',
			3: 'Denied'
		};
		const height = window.innerHeight * 6 / 10;

		return ( 	
			<BootstrapTable
				data={this.props.studentUpdateRequests}
				options={options}
				height={height}
				expandableRow={this.expandableRow.bind(this)}
				expandComponent={this.expandComponent.bind(this)}
				expandColumnOptions={{
					expandColumnVisible: true,
					expandColumnComponent: this.expandColumnComponent.bind(
						this
					),
					columnWidth: 50
				}}
				search
				pagination
			>
				<TableHeaderColumn dataField="id" isKey={true} hidden>
					Request Id
				</TableHeaderColumn>
				<TableHeaderColumn
					dataField="status"
					filterFormatted
					dataFormat={this.enumFormatter.bind(this)}
					formatExtraData={statuses}
					columnClassName={this.styleStatus.bind(this)}
					filter={{
						type: 'SelectFilter',
						options: statuses,
						defaultValue: null
					}}
				>
					Status
				</TableHeaderColumn>
			</BootstrapTable>
		);
	}`

**Comment by prajapati-parth** [comment] 2017-08-24 05:16
Reproducible :+1:.
@Kawirider636 current work around would be to use option `sizePerPageDropDown` and return your own dropdown.

Reference: Please view section **Default Custom SizePerPage DropDown** on [this page](http://allenfang.github.io/react-bootstrap-table/example.html#custom).

Thanks.

**Comment by Kawirider636** [comment] 2017-08-24 15:15
Thank you!

**Comment by AllenFang** [comment] 2017-08-26 06:04
yes, this is a known issue when I stop use `jQuery` and `bootstrap.js` in `react-bootstrap-table`...

**Comment by li164902697** [comment] 2017-10-16 09:33
@AllenFang  how to solve this problem?

**Comment by ziaulrehman40** [comment] 2017-10-18 05:42
@AllenFang Please close duplicate issues for cleanup.

two are: #1691 and #1580 , there might be more.

**Comment by ziaulrehman40** [comment] 2017-10-18 09:22
I had this and a related issue which was arising exactly because this issue is arising, which is that this library does not remove open class from the dropdown when it is closed by clicking outside the dropdown. When dropdown button is clicked it correctly removes open class.

I have overcome this by adding custom dropdown, here is a bootstrap4 dropdown I am using:

```
  renderSizePerPageDropDown(props) {
    return (
      <TableSizeDropdown data={} />
      <span className="dropdown">
        <button className="btn btn-secondary dropdown-toggle"
          type="button"
          id="paginationDropDown"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false">
          { props.currSizePerPage }
        </button>
        <div className="dropdown-menu" aria-labelledby="paginationDropDown">
          {
            props.sizePerPageList.map((n, idx) => {
              return (
                <button className="dropdown-item"
                  key={ idx }
                  type="button"
                  onClick={ () => props.changeSizePerPage(n) }>
                  { n }
                </button>
              );
            })
          }
        </div>
      </span>
    );
  }
```
And binding this with sizePerPageDropDown option like so:

```
opts = {
      ...
      sizePerPageList: [ 10, 20, 50 ],
      sizePerPageDropDown: this.renderSizePerPageDropDown
    };
```

**Comment by AllenFang** [comment] 2017-10-19 05:51
I'm not sure if I gind a global document click event to remove the `open` class is the best solution ?!... actually, the issue just like @ziaulrehman40 said.

anyway, @ziaulrehman40 even you have a custom dropdown, I think the problem still there, right?!

**Comment by ziaulrehman40** [comment] 2017-10-19 05:58
@AllenFang I am not sure(didnt get chance to closely look in the code of react-bootstrap-table) that why open class is not being removed.

This custom dropdown is working perfectly for me. Of-course, because it is custom and not generated by react-bootstrap-table.

And i posted this code just to help anyone struggling with this issue to deal with the problem by temporarily using this custom dropdown.

**Comment by prajapati-parth** [comment] 2017-10-19 07:53
@AllenFang Binding to global document click is definitely not the best solution. In my custom implementation of dropdown for react-bootstrap-table, I attached a blur event to the button element of dropdown that would remove the open class.

**Comment by AllenFang** [comment] 2017-10-23 06:26
@prajapati-parth thanks,,  I will give it a try 👍

**Closed** 2017-10-25 07:27 UTC
Labels: bug

**Comment by AllenFang** [comment] 2017-10-25 07:33
Fixed on `v4.1.1`, now the sizePerPage dropdown work well. Thanks

**Comment by JyotiRani** [comment] 2017-12-06 05:26
@AllenFang i am using v4.2.0 but still sizeperpage dropdown is not working for me. Can you please help me?

**Comment by AllenFang** [comment] 2017-12-06 12:43
@JyotiRani I think this issue was fixed, please give me some information to reproduce your issue.
