### ISSUE TITLE
columnTitle does not show on column that has data format

### ISSUE THREAD

**Issue by sacredMonster** [AllenFang/react-bootstrap-table#1148] opened 2017-03-14 22:50 UTC
I am adding a data format to the column, which basically creates a anchor tag. I still want the column title to appear for this particular column when user hovers over it. However it does not seem to be working. Here is the sample code:

 tfsLink = (cell, row) => {
    const formattedCell = `#${row.id} ${cell}`;
    return `<a href="http://rambo?id=${row.id}" target="_blank">${formattedCell}</a>`;
  };

<TableHeaderColumn dataField="title" dataAlign="left" width="400px" dataFormat={this.tfsLink} columnTitle headerAlign="center">Title</TableHeaderColumn>

Thanks...

**Comment by AllenFang** [comment] 2017-03-18 13:00
sorry for lately reply, could you please check again? I cant reproduce this issue, thanks

**Comment by AllenFang** [comment] 2017-03-18 13:02
or show your example

**Comment by oakley808** [comment] 2017-03-28 17:49
@sacredMonster 
You can handle the html `title` attribute inside your formatting function.
```
const boldDataFormatter = (c, r) => {
  const shouting = c.toUpperCase();
  return (<b title={c}>{shouting}</b>);
};
```

**Comment by AllenFang** [comment] 2017-03-29 14:43
it's right answer, @oakley808 thanks :)  close it and let me know if there's still some problems remain

**Closed by AllenFang** 2017-03-29 14:43 UTC
