### ISSUE TITLE
Support for SelectFilter to use true/false values

### ISSUE THREAD

**Issue by riguy724** [AllenFang/react-bootstrap-table#660] opened 2016-08-26 00:08 UTC
It seems like there is no support for this presently.  I may put a PR together for this, but just figured i'd open it as an issue to see who else is interested in support for this, or has a suggestion for a workaround.

**Comment by AllenFang** [comment] 2016-08-27 03:03
@riguy724, PR is welcome and I'll try to reproduce this issue and figure the root cause. Thanks :)

**Comment by AllenFang** [comment] 2016-08-27 06:11
@riguy724, I'll fix it in next version.

**Comment by AllenFang** [comment] 2016-08-27 13:37
Fixed on ```v2.4.4```.

**Closed** 2016-08-27 13:36 UTC
Labels: bug

**Comment by riguy724** [comment] 2016-08-27 21:18
Thanks @AllenFang , excited to try this out!

**Comment by AllenFang** [comment] 2016-08-28 04:00
@riguy724, there's one thing to notice, on ```v2.4.4``` I move the css files from ```css``` to ```dist``` folder, remember to update the css path. I apologize for it.
