### ISSUE TITLE
Select all and pagination - selecting ALL, not just on current page

### ISSUE THREAD

**Issue by SimonDKnight** [AllenFang/react-bootstrap-table#537] opened 2016-06-27 10:52 UTC
I have a list of items with tick boxes (so I can select multiple items), and I am also using pagination. The problem I have run into is that when I used the tick box to select all it literally selects EVERY item, even those not on the current page(from the pagination). Surely this is a mistake? Surely it should only selection the items on the current page and not ones that are paginated? Is this a bug?

**Comment by AllenFang** [comment] 2016-06-27 12:52
HI @SimonDKnight, This is not a bug, It's absolutely right.

**Comment by SimonDKnight** [comment] 2016-06-27 13:23
Hi, thanks for the fast response. So if I have 100 items, and pagination is set to display 10 at a time, and on page 1 I click the select all checkbox its meant to delete all 100? Surely it should only delete the 10 on that first page?

**Comment by AllenFang** [comment] 2016-06-28 02:08
@SimonDKnight, I think the select all just means **all**, not only in current page. If there're other people have same confuse, I'll consider to separate this functionality.

**Comment by SimonDKnight** [comment] 2016-06-28 02:11
I personally think it is confusing and not something that is standard. For example if your on gmail or hotmail, and then tick the box at the top to select all the emails, it is only selecting those on the current page, not every single email in your inbox.

**Comment by AllenFang** [comment] 2016-06-29 01:52
Your example is great, let my think how to make select all compatible with this requirement.

**Comment by samuelmartineau** [comment] 2016-08-01 16:43
Hi @AllenFang,

I agree with @SimonDKnight for the Gmail use case and I have a question about how select all (not displayed row and show them as selected when you browse the table by the nav)

When you **select all** by the main tick on Gmail, it shows a banner to ask you if you want to select the current page or all records (that proves that it's not clear for everyone :wink: )

![screen shot 2016-08-01 at 18 23 40](https://cloud.githubusercontent.com/assets/5717515/17301088/90ac50ea-5815-11e6-8328-39667b760896.png)

And you can clear it by the same banner after selection
![screen shot 2016-08-01 at 18 23 54](https://cloud.githubusercontent.com/assets/5717515/17301087/90aaeb74-5815-11e6-93fa-8206e435cb4d.png)

I've already done it with the prop **selected** of **selectRow** manually populate during **onSelectAll** callback but I was wondering if there's a more elegant way to do that. What's the current status?

**Comment by AllenFang** [comment] 2016-08-02 12:59
@samuelmartineau, I thinks your solution is only one way to do this. Maybe you can share your examples. BTW, about this issue, I've no plan to do this, because it's a big change for select all behavior. I'm going to support ```v3.0.0``` at first then go back to solve this issue. In my opinion, we need make this feature configurable(The gmail solution is ok, but maybe there's some solution is more better)

**Comment by samuelmartineau** [comment] 2016-08-02 22:42
I am using your component for a corporate project so I can't share it directly but I can make an example as you did on this repo (./examples/js/selection). Are you interested by that?

**Comment by AllenFang** [comment] 2016-08-03 08:07
ok, is it work on your project?

**Comment by SimonDKnight** [comment] 2016-08-03 08:49
@samuelmartineau I would really appreciate it if you could put a quick example in the examples section.

Thanks

**Comment by AllenFang** [comment] 2016-08-03 10:48
@SimonDKnight, I thinks @samuelmartineau is use external selection to control the select all. If his example work, maybe we dont support this feature native.

**Comment by samuelmartineau** [comment] 2016-08-03 12:32
@AllenFang Yes it works for me so I will make an example

**Comment by samuelmartineau** [comment] 2016-08-03 19:57
@AllenFang I made a [PR](https://github.com/AllenFang/react-bootstrap-table/pull/602) with the minimal use case to show how I solved it. Let me know if it's good or not. @SimonDKnight Does #602 answer your issue?
I've updated the doc.

**Comment by AllenFang** [comment] 2016-08-04 01:03
@samuelmartineau, that's awesome. I think this is a workaround for this issue :)

**Comment by AllenFang** [comment] 2016-08-04 15:31
hi all, try the following, I thinks it's more better and match to the @SimonDKnight's requirement
```js
export default class SelectHookTable extends React.Component {

  onSelectAll = (isSelected) => {
    if (isSelected) {
      return this.refs.table.state.data.map(row => row.id);
    }
  }

  render() {
    const selectRowProp = {
      mode: 'checkbox',
      clickToSelect: true,
      onSelectAll: this.onSelectAll
    };

    return (
      <BootstrapTable ref='table' data={ products } selectRow={ selectRowProp } pagination>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}

```

**Comment by AllenFang** [comment] 2016-08-04 15:35
I prefer to close this issue. If any problem or trouble happen, I'll open it!

**Closed by AllenFang** 2016-08-04 15:35 UTC
Labels: discussion, help wanted

**Comment by Saiprasad2021** [comment] 2019-09-09 11:57
Hey how can i do this , actually we are using data-tables plugin . 
here i'm facing same issue if i click on select-all it's selecting current page items , it's not selecting total items..
