### ISSUE TITLE
When adding Icon with onClick event inside row, the rows are not showing...

### ISSUE THREAD

**Issue by israelws** [AllenFang/react-bootstrap-table#812] opened 2016-11-02 16:03 UTC
I'm using react-bootstrap-table - its great!!!

I want to add edit icon in every row, so when the user clicks it will open modal for editing. 
To do so, I added pseudo column with formatter that displays Icon and it is working fine, but when I'm added onClick event with function, the table shows that there are no rows.

the following is sample of my code:

```
<TableHeaderColumn key="editAction" dataField="editId" width="50" dataFormat={this.editFormatter} >

editFormatter(cell, row){
        return <Icon onClick={this.editRow()} glyph="icon-fontello-edit-1"/>;
 }

 editObject(){
        console.log('edit');
 }
```

Am I doing something wrong or is it a bug ?
is there another way to put action icons (clickable) in every row ?

Thanks,
El

**Comment by AllenFang** [comment] 2016-11-03 12:57
> but when I'm added onClick event with function, the table shows that there are no rows.

what's means for "table shows that there are no rows" ?

and how about showing me this ```editRow``` function? 

Thanks :)

**Comment by israelws** [comment] 2016-11-03 13:58
I managed to solve the problem:

```
editFormatter(cell, row) {
        return(
            <ButtonGroup>
                <Button xs outlined onlyOnHover onClick={()=>this.editObject(row)}    bsStyle="green"><Icon glyph="icon-fontello-edit-1"/></Button>
                <Button xs outlined onlyOnHover onClick={()=>this.deleteObject(row)}  bsStyle="danger"><Icon glyph="icon-fontello-trash-1"/></Button>
            </ButtonGroup>
        )
    }

    editObject(row) {
        console.log('edit',row);
    }

    deleteObject(row) {
        console.log('delete object',row);

    }
```

That solve the problem:

```
<TableHeaderColumn key="editAction" dataField="editId" width="120" dataFormat={::this.editFormatter} >
```

binding the editFormatter (`::this.editFormatter`) putted the function in the component's scope, allowing it to "see" the "this.editObject" function.

I guess that the reason I didn't see the rows was because the dataFormat function generated error when rendering the table rows. 

If this is possible, an error message should be caught when rendering the table rows.

thanks for your help

**Comment by AllenFang** [comment] 2016-11-03 15:47
I think the error should be output on console, so I'm not very sure the root cause, but I'm glad that you solve this issue. Close it, Feel free to discuss with me if encounter any problems. Thanks

**Closed by AllenFang** 2016-11-03 15:47 UTC
