### ISSUE TITLE
Click On column text donot trigger onRowSelect

### ISSUE THREAD

**Issue by skrajath** [AllenFang/react-bootstrap-table#999] opened 2017-01-31 08:32 UTC
I have column with dataFormat returning

`<span className="column-select">{this.props.field}</span>`

and the css as below to make it look like clickable

```
.column-select{
	cursor:pointer;
}

.column-select:hover{
	color:#9A144A;
}
```

When clicked on this text, onRowSelect is not getting triggered. Below is the row props

```
handleRowSelect(row, isSelected, e) {
      if (e.target.cellIndex === 0)
           alert(`row clicked`);
    }
const selectRowProp = {
            mode: 'checkbox', 
            hideSelectColumn: true, 
            clickToSelect: true,
            bgColor: 'pink', 
            onSelect: this.handleRowSelect,
            
          };
 <BootstrapTable selectRow={ selectRowProp } pagination={ false }>
<TableHeaderColumn 
                isKey 
                width='350' 
                dataAlign='center'
                dataField='id'
                dataFormat={idFormatter}
                >Payment ID</TableHeaderColumn>
```
but the bgColor: 'pink', gets applied. Am i missing something here?

**Comment by AllenFang** [comment] 2017-01-31 12:14
this may related with https://github.com/AllenFang/react-bootstrap-table/issues/994, I'll fix it soon.

**Comment by AllenFang** [comment] 2017-02-01 08:10
Fixed on `v2.11.0`, check this out and let me know if the problem still remain.

**Comment by skrajath** [comment] 2017-02-01 08:20
Problem still remains.

I have these
```
"react": "^15.4.2",
"react-bootstrap-table": "^2.11.0",
```

**Comment by AllenFang** [comment] 2017-02-01 10:18
ok, are you sure that `handleRowSelect` still not called?

> Also can it be like, onRowSelect should be triggered only when clicked on the formatted text and not any where else in the cell?

I thought when you enable `clickToSelect`, which means you click on the whole row is supposed to be selected instead of specified area or custom formatted, this rule is been clear from this project start

**Closed** 2017-02-01 10:23 UTC
Labels: bug, duplicate, inprocess

**Comment by AllenFang** [comment] 2017-02-01 10:29
make sure is that `handleRowSelect` not called or your `alert` not popup. I cant' reproduce this issue, I've a custom cell by `dataFormat` and I make the font much bigger so that I can **click** on them, after my testing, the `onSelect` callback was being called successfully. Close it.

**Comment by skrajath** [comment] 2017-02-01 11:12
`handleRowSelect` is not called for sure. I tried with increasing font as well. :(

**Comment by AllenFang** [comment] 2017-02-01 12:25
could you please show me this formatter `idFormatter` ?

**Comment by skrajath** [comment] 2017-02-02 03:34
Here is the formatter
```
class IdFormat extends React.Component {
  render() {
    return (
      <span className="column-select">{this.props.field}</span>
    );
  }
}

function IdFormatter(cell,row){
     return (
        <IdFormat field={ cell }/>
      );
}
```
and the css

```
.column-select{
	cursor:pointer;
}

.column-select:hover{
	color:#9A144A;
}
.column-select{
	cursor:pointer;
}

.column-select:hover{
	color:#9A144A;
}

```

and this

```
 <TableHeaderColumn 
                        isKey 
                        width='480' 
                        headerAlign='center' 
                        dataAlign='left'
                        dataField='Id'
                        dataFormat={IdFormatter}
                        >ID</TableHeaderColumn>
```

**Comment by AllenFang** [comment] 2017-02-02 16:43
@skrajath, I already follow all your code again, but still can't reproduce this issue, any idea or a simple repo for me to test?

**Comment by skrajath** [comment] 2017-02-06 09:59
@AllenFang  Here is sample repo i created. https://github.com/skrajath/react-bootstrap-custom-tableheader

**Comment by AllenFang** [comment] 2017-02-06 12:53
Your example can not run correctly(`npm run dev` fail), Seems like can not recognize the JSX, please configure as well.

BTW, I copy your code and test it again but the functionality is still work well, the `handleRowSelect` has been called, 

But you code is very strange:
1. you disable pagination, but give pagination options
2. you enable remote mode, but you dont have any store to handle the data
3. the selection column disappear without any error, I just guess cause by 1 or 2

Anyway, I've no time to debug your application to figure why `npm run dev` fail and I have no time to think why you have these configuration and these configuration is different with you mentioned above....

so just give me a correct code and correct command and let me reproduce, 

 this issue should be fixed, because other people have report me the bug is gone.

Anyway, I want a clear, correct, executable and simple example or repo to reproduce this issue, I really have no time to waste on here

**Comment by skrajath** [comment] 2017-02-06 16:58
@AllenFang Sorry for the confusion. Here is a new repo and the readme file has 3 simple steps to run the sample
https://github.com/skrajath/react-bootstraptable-customheader

Let me know if you need any more information

**Comment by AllenFang** [comment] 2017-02-07 13:05
HI, I still got following error:

<img width="593" alt="2017-02-07 9 02 41" src="https://cloud.githubusercontent.com/assets/5351390/22692190/d63700a8-ed78-11e6-98ea-104afdf72dd5.png">

BTW, I still copy you code again and test on my local, the `handleRowSelect` was being called successfully.

**Comment by skrajath** [comment] 2017-02-09 11:05
I understand the copy paste is working for you. What looks strange is, what is that I am missing in my app.
Also the repo is updated (sorry again). Can you please run again.
https://github.com/skrajath/react-bootstraptable-customheader

**Comment by skrajath** [comment] 2017-02-10 11:12
My global `webpack-dev-server` version is `4.0.3`.
Please check with this, in the mean time I will get the repo fixed.
