### ISSUE TITLE
sortFunc not triggered when using dataFormat

### ISSUE THREAD

**Issue by vitortmdiniz** [AllenFang/react-bootstrap-table#1066] opened 2017-02-20 17:43 UTC
I'm trying to implement  a custom sort function for a few rows in my table, but the function is never called when i'm also using dataFormat. When i'm not using dataFormat it works okay. Is there anyway i can use dataFormat and then sort based on it?

**Comment by AllenFang** [comment] 2017-02-22 01:11
could you please show your examples? it was supposed to be simple and minimal for me to reproduce it, thanks :)

**Comment by vitortmdiniz** [comment] 2017-03-02 15:28
Yes, sure! It's not getting into ordenarLC.
  ```

formatarLC(areas)
 {
        let nota = null;
        areas.map((area)=>{
            if(area.areaConhecimentoId === 424)
                nota= area.porcentagemAcerto + '%'}
        );
        if(nota)
            return nota;
        return 'Prova não realizada'

}
ordenarLC(a,b,order)
{
     console.log('oi');
 }

   
render() {

 return (
            <div>
                <BootstrapTable data={this.props.resultados.alunos}  striped hover search searchPlaceholder={'Pesquisar por aluno'}>
                    <TableHeaderColumn isKey dataField='alunoNome' dataSort >Nome</TableHeaderColumn>
                    <TableHeaderColumn dataField='notasAreas'  dataFormat={this.formatarLC} dataSort sortFunc={this.ordenarLC}>Linguagens e Códigos</TableHeaderColumn>
                    <TableHeaderColumn dataField='notasAreas' dataFormat={this.formatarMat} >Matemática</TableHeaderColumn>
                    <TableHeaderColumn dataField='notasAreas' dataFormat={this.formatarCN} >Ciências da Natureza</TableHeaderColumn>
                    <TableHeaderColumn dataField='notasAreas' dataFormat={this.formatarCH} >Ciências Humanas</TableHeaderColumn>
                    <TableHeaderColumn dataField='notasRedacao' className="text-center" dataFormat={this.formatarRedacao} >Redação</TableHeaderColumn>
                    <TableHeaderColumn dataFormat={this.formatarFolhaRespostas}>Relatório do Aluno</TableHeaderColumn>

                </BootstrapTable>
            </div>
        );
    }
```

**Comment by AllenFang** [comment] 2017-03-03 13:07
ok, I'll check this out, thanks 👍

**Comment by AllenFang** [comment] 2017-03-04 09:33
@vitortmdiniz, the root cause is you assign duplicate `dataField` on same table, it will cause some filter/search/sort fails, it's a known issue and may not be fixed in near future because it's a big change, so I'll fix it in the future.

Anyway, I suggest you to flat or merge your data with a appropriate format to table is a good workaround now. 

BTW, you can still fix this issue by put the `sortFunc` on last `notasAreas` field, I guess it can work.

Let me know if you got any question. thanks

**Closed by AllenFang** 2017-03-04 09:33 UTC
Labels: inprocess

**Comment by AllenFang** [comment] 2017-03-04 09:35
https://github.com/AllenFang/react-bootstrap-table/issues/1113

**Comment by BhumiSukhadiya** [comment] 2017-05-04 08:25
I want to add sorting on all data fields with same name where datafield is an object.
is there any solution for this issue?

**Comment by vitortmdiniz** [comment] 2017-05-19 14:53
Thanks! But it doesn't work when i put the sortFunc on last notasAreas and i'm also using sortFuncExtraData for all collumns, it's always passing the last sortFuncExtraData to the sortFunc independently of the column i'm sorting. Any way to fix this?

**Comment by AllenFang** [comment] 2017-05-20 08:48
sorry @vitortmdiniz, we doesn't support duplicate `dataField` until now. I'll have a big impact on code base. so I still consider to support this feature.

**Comment by droyuki** [comment] 2017-09-14 05:55
what's the progress now?

**Comment by AllenFang** [comment] 2017-09-15 14:09
As I mention on [homepage](https://github.com/AllenFang/react-bootstrap-table), we already move to `react-bootstrap-table2`, this feature will be consider to implement in there. and I'm almost focus on development on `react-bootstrap-table2`, so if any feature request, you can also open issue on here, but its still work in progress.
