### ISSUE TITLE
Do you know why filters do not work with dynamically generated columns?

### ISSUE THREAD

**Issue by rrameshkumar76** [AllenFang/react-bootstrap-table#614] opened 2016-08-09 01:21 UTC
Do you know why filters do not work with dynamically generated columns? I followed the steps as in https://github.com/AllenFang/react-bootstrap-table/issues/450 , the dynamic columns work great. 

Its only filters that do not work(Example numeric filter). It displays the filter controls , but does not do the filter operation.

**Comment by AllenFang** [comment] 2016-08-09 01:22
@rrameshkumar76, maybe this is an issue, could you please show me an example for reproducing it?  Thanks :)

**Comment by rrameshkumar76** [comment] 2016-08-09 13:46
It works in a standalone component, I will verify why the issue happens within our component and let you know and close the issue.

**Comment by rrameshkumar76** [comment] 2016-08-09 14:38
The issue was in our side in the way we rendered the component. Thanks for all the help.

**Comment by AllenFang** [comment] 2016-08-10 01:06
Great :)

**Comment by oeph** [comment] 2016-10-18 12:36
I stumbled on this problem myself and i think there is a problem with the binding of the handleFilter function.
So even that this issue is closed, i think the initial problem still remains and should be fixed.
@AllenFang I can provide you with a PR if u want to

**Comment by AllenFang** [comment] 2016-10-18 12:55
@oeph, PR is welcome, but maybe an example which can reproduce this issue is also well, because this can help me to find the root cause!

Thanks you 👍

**Comment by oeph** [comment] 2016-10-18 13:41
@AllenFang I try to make a simple example from my codebase.
The root cause is, that the handler for filtering events is set in the constructor. But if you create the Table first and fetch data + add columns, the handler already tried to bind -> found no filter -> skip the binding. The binding of the handler is not called again if props/columns change.

**Comment by oeph** [comment] 2016-10-19 08:17
@AllenFang example https://jsfiddle.net/03h4dvav/

the handler for the filter change event is not working. If you insert the columns at the start, the filter works. I will make a PR for this problem.

**Closed** 2016-11-02 15:38 UTC
Labels: inprocess

**Comment by AllenFang** [comment] 2016-11-02 15:52
Fixed on ```v2.5.7```. Thanks @oeph's contribution 💯
