### ISSUE TITLE
Get an error after enabling insertRow.

### ISSUE THREAD

**Issue by fscnick** [AllenFang/react-bootstrap-table#1087] opened 2017-02-26 09:36 UTC
I get the following error after enabling 'insertRow' props.
```
Uncaught (in promise) Error: react-modal: You must set an element with `Modal.setAppElement(el)` to make this accessible
    at validateElement (ariaAppHider.js:31)
    at show (ariaAppHider.js:18)
    at Object.toggle (ariaAppHider.js:26)
    at Object.renderPortal (Modal.js:100)
    at Object.componentDidMount (Modal.js:66)
    at react-dom.js:4719
    at measureLifeCyclePerf (react-dom.js:4529)
    at react-dom.js:4718
    at CallbackQueue.notifyAll (react-dom.js:948)
    at ReactReconcileTransaction.close (react-dom.js:11398)
```

<br/>

The table content shows correctly, but the pagination is malfunctional.
The snippet is below.
```javascript
<BootstrapTable  data={ this.state.datas } pagination striped hover condensed insertRow={ true } options={this.options}>
		<TableHeaderColumn width='100' dataField='key'  isKey autoValue={true} hidden hiddenOnInsert>rID</TableHeaderColumn>
		<TableHeaderColumn width='150' dataField='date' editable={this.editable.date} dataSort>Date</TableHeaderColumn>
		<TableHeaderColumn width='100' dataField='kind' editable={this.editable.kind}>Kind</TableHeaderColumn>
		<TableHeaderColumn width='150' dataField='note' editable={this.editable.note}>Note</TableHeaderColumn>
		<TableHeaderColumn width='150' dataField='number' editable={this.editable.number} dataSort>number</TableHeaderColumn>
		<TableHeaderColumn width='150' dataField='picture' hidden hiddenOnInsert>Picture</TableHeaderColumn>
		<TableHeaderColumn width='100' dataField='tag' editable={this.editable.tag}>Tag</TableHeaderColumn>
		<TableHeaderColumn width='100' dataField='type' editable={this.editable.type}>Type</TableHeaderColumn>
</BootstrapTable>
```

```javascript
this.editable = {
            date: {type: 'datetime'},
            kind: {type: 'select', options: {values: this.selections.kinds}},
            tag: {type: 'select', options: {values: this.selections.tags}},
			note: {validator: this.fieldNoteValidator},
			number: {validator: this.fieldNumberValidator},
			type: {validator: this.fieldTypeValidator}
        };
```

What do I miss ?

**Comment by AllenFang** [comment] 2017-03-02 04:05
@fscnick, sorry for lately reply due to my long trip.

Could you help me to check the `react-modal` version in your env(node_module)? `react-modal` is one of a dependency in `react-bootstrap-table`

and I'll check this out also, thanks

**Comment by fscnick** [comment] 2017-03-02 16:49
@AllenFang Don't be.

I'm not using `nodejs` for development. Get dependencies from CDN. `react-modal` is not included. 
I have included it explicitly and got the same error.  Is there other method to show the version on Chrome?

The following is the relative about `react`.
```html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/redux/3.6.0/redux.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react-redux/5.0.2/react-redux.js"></script>
```

**Comment by AllenFang** [comment] 2017-03-03 13:19
never mind for the `react-modal` version and I think this is an issue about `react-modal`, https://github.com/reactjs/react-modal/issues/133#issuecomment-265440560 and https://github.com/reactjs/react-modal/issues/267

did you have an examples on fiddlejs or a static html with js? I wanna check it, thanks

**Comment by fscnick** [comment] 2017-03-04 17:36
Here is [the example](https://jsfiddle.net/w765zkd8/).

Start it by clicking `Render`. Then, `RecordManager` receives a new props. At the end of `doPrepareData()`, `forceUpdate()` is invoked where the error happens.

Although the code is slightly tedious, I hope this would give some help.

**Comment by AllenFang** [comment] 2017-03-06 12:49
@fscnick, thanks, I roughly check your code but still got no idea about this issue. But I think there's no problem on `react-bootstrap-table`, I guess maybe is that you are not use node(npm) to develop and cause some wired problem, or maybe is about the redux. because redux application need render the Provider on DOM and according to the issue I mentioned before, this have a lots of chance for this issue.

I'll spend some time to try it again, but not sure I can find the root cause and I'm also busy here so ma have some delay.. 

Sorry

**Comment by fscnick** [comment] 2017-03-07 16:57
No need to apologize. This a nice library.

I'm glad you are willing to take some time to do that. And hope it would not bother you too much.

I will try it, too.

**Comment by dminuoso** [comment] 2017-03-13 23:20
I can reproduce the issue with a simplistic app

```import 'react-bootstrap-table/dist/react-bootstrap-table-all.min.css';

/* Libraries */
import React from 'react';
import ReactDOM from 'react-dom';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

class Table extends React.PureComponent {
  render() {
    return(
      <BootstrapTable data={ [{id:1}] } insertRow >
        <TableHeaderColumn hidden={true} dataField='id' isKey />
      </BootstrapTable>
    );
  }
}

window.mountReact = (element) => {
  ReactDOM.render((
		<Table />
  ), element);
}
```
```json
{
  "name": "apax",
  "license": "MIT",
  "dependencies": {
    "react": "~15.4.2",
    "react-router": "~3.0.2",
    "stats-webpack-plugin": "^0.4.3",
    "webpack": "^1.14.0",
    "webpack-dev-server": "^1.16.2"
  },
  "devDependencies": {
    "babel-core": "~6.22.1",
    "babel-loader": "~6.2.10",
    "babel-preset-es2015": "~6.22.0",
    "babel-preset-react": "~6.22.0",
    "css-loader": "~0.26.1",
    "react-bootstrap-table": "~3.1.0",
    "react-dom": "~15.4.2",
    "redux": "~3.6.0",
    "style-loader": "~0.13.1"
    
  }
}```

**Comment by AllenFang** [comment] 2017-03-14 03:06
@dminuoso, thanks for your investigation, but what's kind of situation will get this error?

**Comment by dminuoso** [comment] 2017-03-14 04:46
The problem happens whenever the library is loaded in a place without document available such as loading the library in a <head> node or server-side rendering.

There's a few workarounds such as calling Modal.setAppElement(elem) at least once from **anywhere** when document actually exists, such as any componentWillMount callback. But it's a hack with some drawbacks.

However I have a true fix for react-modal for which I will submit a PR later today.

**Comment by AllenFang** [comment] 2017-03-16 00:10
got it, thanks you 👍 👍

**Comment by fscnick** [comment] 2017-03-26 08:29
I see no PR about this. Is it applied?

**Comment by AllenFang** [comment] 2017-03-26 11:55
@fscnick, please wait.

**Comment by fscnick** [comment] 2017-03-26 13:54
Sorry for that. There is no response for a while. 

I just wonder to know it is still processing or accepted. I am not sure if I get loss something or not.

**Comment by dminuoso** [comment] 2017-03-26 19:55
This PR basically addresses this issue in a more flexible way.

https://github.com/reactjs/react-modal/pull/360

This was the patch I had originally in mind:
https://github.com/dminuoso/react-modal/commit/b283423d2fdd60225edd4e887b777430a0708d95

**Comment by AllenFang** [comment] 2017-03-27 13:01
so this issue seems like fixed on `react-model`?

**Comment by dminuoso** [comment] 2017-03-27 20:04
As it stands right now you will have to provide a getAppElement prop to <Modal /> in the upcoming version.

**Comment by AllenFang** [comment] 2017-03-28 15:33
@dminuoso, I'll have some investigation in near future and fix it, thanks a lots

**Comment by came** [comment] 2017-12-07 18:29
After upgrading to react 16.2 I get exactly the same error. I've updated to "react-bootstrap-table": "^4.2.0". In my own coding I also use "react-modal": "^3.1.7"

**Comment by AllenFang** [comment] 2017-12-12 13:02
@came sorry for lately reply, `v4.3.0` have newest dependency on `react-modal@3.1.7`, you can check this.

**Closed by AllenFang** 2017-12-12 13:02 UTC
Labels: bug, in progress
