### ISSUE TITLE
sizePerPageList issue: 'close' class gets erased

### ISSUE THREAD

**Issue by pinkynrg** [AllenFang/react-bootstrap-table#1257] opened 2017-04-25 21:08 UTC
Good afternoon,

I just made big changes to the project I'm working on, so I can't understand if the issue I'm having is due to the changes I made or the actual library version.

What is happening is that I click on the list (which adds an 'open' class to it). Once the parent component updates the state, the child re-render, and the list closes (the class 'open' disappears). This wasn't happening with the old version of my software.

**Comment by AllenFang** [comment] 2017-04-26 15:13
yes, after `v3.0.0` will have this effect. The problem is in `v3.0.0` I remove the `bootstrap.js` and `jquery` dependency, so I need to control the open/close state in react component. I'll try to improve it but not sure can fix it. Let me know if you have any concern, thanks

**Comment by AllenFang** [comment] 2017-04-26 15:17
ok, after a quick look, I think it's hard to fix, because it's native behavior for bootstrap, if dropdown open  and you click outside of dropdown, it will close.

**Comment by pinkynrg** [comment] 2017-04-26 15:27
The thing is that I'm not click anywhere for it to close.

I have this table that updates its content every 3 seconds lets' say. let's say that I click on the pageSizeList bootstrap list, once the 3 seconds expire the list will close by itself, without me clicking anywhere.

**Comment by AllenFang** [comment] 2017-04-27 10:07
got it, I'll spend some time to check this one.

**Comment by AllenFang** [comment] 2017-05-06 08:31
Fixed on `v3.3.1`, enable `options.keepSizePerPageState`. thanks

**Closed** 2017-05-06 08:31 UTC
Labels: enhancement, inprocess
