### ISSUE TITLE
property of undefined after trying to add a row after deleting everything.

### ISSUE THREAD

**Issue by fudgecakes** [AllenFang/react-bootstrap-table#1010] opened 2017-02-03 23:10 UTC
￼First I delete everything from the table by selecting all the checkboxes, I deleted everything using my own delete function which just clears out the array. Then I try adding an item which updates an array and re renders the component and I get the following error. 

Uncaught TypeError: Cannot read property 'name' of undefined  (name is a dataField)
at TableBody.<anonymous> 
at Array.map (native)
at TableBody.<anonymous> 
at Array.ma (native)
at TableBody.render

However, after refreshing, then I'm able to start adding items again without the undefined error.

**Comment by AllenFang** [comment] 2017-02-04 12:23
@fudgecakes, could you please show you code?  thanks, keep your code simple and minimal.

**Comment by fudgecakes** [comment] 2017-02-05 06:00
Sorry Im not able to show any code. Is there a way to customize the functionality of the delete button and add button? Also in V3.0.0 release, I will be able to add my own buttons to the action bar right?

**Comment by AllenFang** [comment] 2017-02-06 13:08
> Sorry Im not able to show any code

ok, because I cant reproduce this issue so I'll close it, but is welcome to open it anytime if you can provide more information



> Is there a way to customize the functionality of the delete button and add button

Yes, you can do i on `v3.0.0., the newest beta version is https://github.com/AllenFang/react-bootstrap-table/releases/tag/v3.0.0-beta.9 and these is example you can check for customization [delete button](https://github.com/AllenFang/react-bootstrap-table/tree/v3.0.0-dev/examples/js/custom/delete-button) and [add button](https://github.com/AllenFang/react-bootstrap-table/tree/v3.0.0-dev/examples/js/custom/insert-button)



> Also in V3.0.0 release, I will be able to add my own buttons to the action bar right?

Of cause you can do it on `v3.0.0`, check [example](https://github.com/AllenFang/react-bootstrap-table/tree/v3.0.0-dev/examples/js/custom/toolbar)

**Closed by AllenFang** 2017-02-06 13:08 UTC
