### ISSUE TITLE
There is no data to display when using props from Reducer

### ISSUE THREAD

**Issue by electrozed** [AllenFang/react-bootstrap-table#1507] opened 2017-07-24 15:49 UTC
I have a main Component :

```javascript
class MainComponent extends Component {

    componentWillMount(){
            this.props.getData()
    }
  
    _renderTableWithData(){

        if(this.props.data !== null){
            return(
                <TableComponent data={this.props.data}/>
            )
        }
        else{
            return null
        }
    }

    render() {
        return (
            <div>
                {this._renderTableWithData()}
            </div>
        )
    }
}
```

inside the TableComponent:

```javascript
class DojoAdminTable extends Component {

    selectRowProp = {
        mode: 'checkbox',
        bgColor: config.style.warningColor

    };
    cellEditProp = {
        mode: 'click',
        blurToSave: true
    };

    render() {
        return (
            <BootstrapTable data={this.props.data}
                            selectRow={this.selectRowProp}
                            cellEdit={this.cellEditProp}
                            options={{noDataText: 'אין מתאמנים בדוג׳ו זה'}}>
                <TableHeaderColumn hidden isKey dataField='id' dataAlign="right"
                                   thStyle={{'color': config.style.textColor}} tdStyle={{
                    'fontWeight': 'lighter',
                    'fontSize': 12,
                    'color': config.style.textColor,
                }}>
                </TableHeaderColumn>
            </BootstrapTable>
        )
    }
}
```
for 100% i have data in this.props.data but when i render the table component getting a message : 
There is no data to display
the data look like this : 
```javascript
this.props.data = [{
id:1,
test:'test'
}]
```

**Comment by thundermiracle** [comment] 2017-07-26 00:08
What about set data by setState to test whether the problem is because of datatable or caused by redux?

**Comment by AllenFang** [comment] 2017-07-29 08:55
@thundermiracle I am not sure if this issues is about `react-bootstrap-table` or not. Provide your repo for me to reproduce your issues. thanks

**Comment by thundermiracle** [comment] 2017-07-29 09:18
@AllenFang This is not my issue. :)
@electrozed It's your turn now

**Comment by AllenFang** [comment] 2017-07-31 14:31
@thundermiracle sorry,  I pin wrong people.... xD

Le me close this issues and wait @electrozed  back, thanks

**Closed by AllenFang** 2017-07-31 14:31 UTC

**Comment by electrozed** [comment] 2017-07-31 15:33
sorry for the troubles i was away 
the problem was with firebase async function 

the redux thunk dispatch append before firebase finished
thanks !

**Comment by AllenFang** [comment] 2017-08-02 14:46
👍
