### ISSUE TITLE
options.page property is not respected

### ISSUE THREAD

**Issue by riguy724** [AllenFang/react-bootstrap-table#763] opened 2016-10-06 18:50 UTC
I've implemented some remote loading of data for a large table I'm working with, everything seems to be working great with the data loading and events, however the paginator keeps on "jumping" back to page 1 when I click on something.  I'm setting this through the `options={{page: this.props.page}}` property on BootstrapTable, but when I set it to `page: 3` for example, page 1 stays selected.

Any ideas?  If anyone wants screenshots / code that does this I can flush this out in more detail, just let me know :)

Thanks!

**Comment by AllenFang** [comment] 2016-10-08 06:14
> Any ideas? If anyone wants screenshots / code that does this I can flush this out in more detail, just let me know :)

it's welcome!  more detail more better

**Comment by aghreed** [comment] 2016-11-07 23:02
Ran into this one myself - @riguy724 try using the prop name of `currentPage`, not `page`.

**Comment by aghreed** [comment] 2016-11-07 23:06
However, @AllenFang it does look like the documentation on this is currently incorrect.

See: http://allenfang.github.io/react-bootstrap-table/docs.html

**Comment by AllenFang** [comment] 2016-11-08 13:35
@aghreed, how did you set ```currentpage``` to control?  In my opinion, only the ```page``` in ```options``` is only way to configure the default page.

Actually, there's a ```currPage``` in table state, you can change it, and it only work for changing page but the date is still the data of previous page,

**Comment by aghreed** [comment] 2016-11-09 18:58
Yep. @AllenFang you are correct. I was mistaken. My apologies!

**Comment by neroleung** [comment] 2016-12-05 19:07
I just ran into this issue in my project. Haven't had time to find out exactly why yet. But I have found a workaround. If you assign a ref to the table, you can do: 

```
this.refs.table.handlePaginationData(3, this.refs.table.props.options.sizePerPage);
```

**Comment by AllenFang** [comment] 2016-12-06 15:53
@neroleung, could you please give me a minimal and simple code which can reproduce this issue? Thanks :)

**Comment by neroleung** [comment] 2016-12-07 22:54
@AllenFang, I was going to add an example in my fork in the gh-pages. But how did you pack thing into the `bundle.js` file? Webpack? Please let me know if there's any instructions around. Thanks!

**Comment by AllenFang** [comment] 2016-12-08 15:07
@neroleung, you just give me the code(Ensure it can reproduce this issue) and I'll pack it :)  You can also post here if it's very small and simple

**Comment by neroleung** [comment] 2016-12-12 20:55
@AllenFang, take a look at this https://neroleung.github.io/react-bootstrap-table/nero_examples.html. I re-used and just modified the remote-paging example a little bit. Notice the options - `page` is 2. The pagingation is at page 2 at the bottom. But the data being shown is page 1.

Similar situation happens if you ajax in the data, except that the pagination wouldn't point to page 2. Because by the time the Pagination is render, the ajax get would still not be done yet.

**Comment by AllenFang** [comment] 2016-12-13 15:03
@neroleung, Actually, ```remote``` means you need to handle the data changing every time, so in your example, when you give page 2, you should give the data corresponding to page 2, for example,
page 1 > row 0 ~ row 4
page 2 > row 5 ~ row 9

Notice [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-paging.js#L30-L44), no matter page or sizePerPage change, you need to reassign the data for ```react-bootstrap-table```.

This is an advantage with ```remote``` on pagination, because ```react-bootstrap-table``` always handle the data which in current page, we dont hold all the data and do pagination inside.

For you example, you just slice the correct rows in the constructor:
```js
super(props);
    this.products = getProducts();
    const currentIndex = (this.props.currentPage - 1) * this.props.sizePerPage;
    this.state = {
      data: this.products.slice(currentIndex, currentIndex + this.props.sizePerPage),
      totalDataSize: this.products.length,
      sizePerPage: this.props.sizePerPage,
      currentPage: this.props.currentPage
    };

```

**Closed by AllenFang** 2016-12-13 15:03 UTC
